- name: Reset cluster
  ansible.builtin.command:
    cmd: kubeadm reset --force

- name: Delete K8S folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/cni/net.d"
    - "/home/{{ ansible_user }}/cluster_initialized.txt"
    - "/etc/kubernetes"

- name: Initialize the cluster
  ansible.builtin.command:
    cmd: kubeadm init # --pod-network-cidr=10.244.0.0/16
  args:
    creates: "/home/{{ ansible_user }}/cluster_initialized.txt"
  register: cluster_initialized_output

- name: Create file to inform previous task
  become: false
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/cluster_initialized.txt"
    state: touch
    mode: "0644"
  when: cluster_initialized_output.rc ==0

- name: Create .kube directory
  become: false
  # become_user: "{{ ansible_user }}"
  ansible.builtin.file:
    path: $HOME/.kube
    state: directory
    mode: "0755"

- name: Copy admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Print join command
  ansible.builtin.debug:
    msg: "{{ cluster_initialized_output.stdout_lines[-2:] }}"

- name: Save output to a local file
  ansible.builtin.copy:
    content: "{{ cluster_initialized_output.stdout_lines[-2:] | join('\n') }}"
    dest: ./k8s_join_command.sh
  become: false
  delegate_to: localhost
  run_once: true

- name: Install K8S network
  become: false
  ansible.builtin.command:
    cmd: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
