- name: "Config :: Disable swap immediately"
  become: true
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: "Config :: Remove swap entry from /etc/fstab"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/fstab"
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: true
    state: present

- name: "Config :: Add the kernel modules needed by containerd"
  become: true
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - overlay
    - br_netfilter

- name: "Config :: Set Kubernetes networking settings"
  become: true
  ansible.posix.sysctl:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: true
  loop:
    - { key: "net.bridge.bridge-nf-call-ip6tables", value: 1 }
    - { key: "net.bridge.bridge-nf-call-iptables", value: 1 }
    - { key: "net.ipv4.ip_forward", value: 1 }
